### PR TITLE
[UPDATE] Set public inheritance for optional on Field.

### PR DESCRIPTION
**Pull request by jpvanoosten**
Remove private inheritance on optional for Field struct template.

### CODE REVIEW

**Comment by jpvanoosten** [comment]
This is a nice to have feature so that Fields can be treated as optional and allows for a more standard syntax on Fields.

**Comment by Madour** [comment]
The reasons why optional is privately inherited is mainly to avoid coupling the Field interface to the optional interface.

Right now, I use an external dependency to provide the optional class, but in the future this might change. And when it changes, by having limited the Field interface I know it won't break the existing code of users.

To check and get the value of a field, you can use `Field<T>::is_null`, `Field<T>::value` and also `Field<T>::value_or`.

For example, if your typical optional use was `.isSomething = field ? *field : false`, you can instead use the equivalent from the Field interface: `.isSomething = !field.is_null() ? field.value() : false`.

Or even better, a shortcut version: `.isSomething = field.value_or(false)`.

That being said, I will add a CMake option to enable the full optional interface in Field (by default, it will be disabled).

**Comment by Madour** [comment]
This request was addressed in #29.

You can now pass the cmake option `-DLDTK_FIELD_PUBLIC_OPTIONAL` to let Field inherit publicly from optional.

**Comment by jpvanoosten** [comment]
Thanks. I'll revert my branch and use `field.value_or` instead.

**Pull request closed without merging**
